### ISSUE TITLE
Not support frida mono api

### ISSUE THREAD

**Issue by JeelsBoobz** [Xposed-Modules-Repo/me.jsonet.jshook#19]
Not support frida mono api script 😔

**Comment by etjson** [comment]
Thank you very much for your attention to jshook. There are still many shortcomings, and the new version 1.1 is being refactored with kotlin. If you are interested after the release of version 1.1, you can participate in the development of this app together.

**Comment by etjson** [comment]
The 1.0 series version code is very irregular, so this is a failed version. I hope it can be recognized in the 1.1 series, so that it can be successfully open sourced.

(#^.^#)

Looking forward to your continued attention to jshook
