### ISSUE TITLE
Installation Issue of JShook Magisk Module

### ISSUE THREAD

**Issue by kyzsuukii** [Xposed-Modules-Repo/me.jsonet.jshook#21]
I am facing an issue while trying to install JShook Magisk Module on my Android device. After installation, zygisk stopped or conflicted, causing zygisk to fail to run.

![Screenshot_20230416-005425_Magisk](https://user-images.githubusercontent.com/110718021/232245121-bdfbc135-a14d-41cf-8158-c9f6d6f36f33.png)
![Screenshot_20230416-005420_Magisk](https://user-images.githubusercontent.com/110718021/232245134-ab415276-23e8-40ed-9d40-a37efc71ccf9.png)

**Comment by etjson** [comment]
I need more device information to locate the problem, you can join the communication group to report the problem
