### ISSUE TITLE
免root模式下，是否支持其他免root框架

### ISSUE THREAD

**Issue by yinsel** [Xposed-Modules-Repo/me.jsonet.jshook#22]
对于某些应用lspatch注入会闪退不兼容，而太极却可以，想问一下是否支持其他框架

**Comment by etjson** [comment]
免root环境也可以考虑使用光速虚拟机或者va框架产品，太极确实没有适配，我会在后续版本中完成，感谢关注，方便的话加下tg群交流，github我不经常看。

**Comment by yinsel** [comment]
好的👌即刻申请加入

**Comment by DuTh126** [comment]
其实可以用 github机器人来链接这个地址 然后回复等相关操作都可以在群组里完成
