### ISSUE TITLE
非常有创意

### ISSUE THREAD

**Issue by rxzcums** [Xposed-Modules-Repo/me.jsonet.jshook#4]
表达感谢和钦佩之情，这样很多人都可以hook了。希望再多一些简易的教程，我再学习。

**Comment by etjson** [comment]
谢谢，可以的话关注一下电报频道或加一下电报交流群。

**Comment by rxzcums** [comment]
> 谢谢，可以的话关注一下电报频道或加一下电报交流群。

收到👍
